Refactored OOA
GibbonEdu/module-IBDiploma pull request #1
Opened 2019-03-05 10:03 UTC by powertashton

student_manage_edit
student_manage_delete
student_manage_add
staff_manage_addProcess
staff_manage_edit
staff_manage_delete
staff_manage_add
cas_supervisor
cas_supervisor_invite
cas_student_reflections_delete
cas_student_reflections_add
cas_student_myCommitments_edit
cas_student_myCommitments_delete
cas_student_myCommitments_add
cas_student_interview3
cas_student_interview2
cas_adviseStudents_details

manifest

These files have been altered to OO PHP from Legacy. 
I have taken the old legacy forms, updated so that they use the new form object. Changes on the pages above.

2019-03-07 02:20 UTC, SKuipers requested changes
Hi Ashton,

This PR is looking great! You certainly have a handle on how the Form classes work 👍 I've added a few notes and suggestions. Is this a one-off project or would you be interested in taking the next steps for refactoring this module? There's a set of Table OO classes, as well as some Gateway classes that would be a great next step.

A couple other overall notes on code style:
- You'll see a lot of the old code uses tabs for indentation. We've since set a standard at 4 spaces instead of tabs. If your code editor has an automatic convert tabs to spaces tool, it helps to run this on any files you change to improve things as we go.
- If you see any `__()` methods in the code still using `__($guid, ` feel free to remove the $guid parameter, it's deprecated now and we're aiming to remove it from the codebase as a whole.

2019-03-07 02:20 UTC, SKuipers commented on IB Diploma/CHANGELOG.txt
> +v1.0.11
Feel free to kick this up to the [next minor version](https://semver.org/), v1.1.00 👍 I think the refactoring you've done is big enough in scope.

2019-03-07 02:20 UTC, SKuipers commented on IB Diploma/cas_adviseStudents_details.php
> +                                $valuesNum = 'even';
There's a `colorOddEven` css class that can replace any of the `$count % 2` etc code for these kinds of tables. Even better, there's a whole new set of Table OO classes. Perhaps that could be step 2 for your refactoring? 😃 give a shout if you're interested and I'd be happy to share the docs & some pointers.

2019-03-07 02:20 UTC, SKuipers commented on IB Diploma/cas_adviseStudents_details.php
> +					$form = Form::create('action', $_SESSION[$guid]['absoluteURL'].'/modules/'.$_SESSION[$guid]['module'].'/cas_adviseStudents_detailsStatusProcess.php', "post");
The 'action' in `Form::create('action', ...` is the ID of the table, it helps to add something descriptive like 'casStatus'. It not only helps readability-wise, but also to keep any of the JS separate when there could be more than one form or table on the page.

2019-03-07 02:20 UTC, SKuipers commented on IB Diploma/cas_adviseStudents_details.php
> +                                	echo "2_outcome".$i;
Is this a debug output? It seems a bit out of place, hard to tell in the diff-view though 🤔

2019-03-07 02:20 UTC, SKuipers commented on IB Diploma/cas_adviseStudents_details.php
> +							// HACK: Otherwise FastFinder width overrides this one :(
Love that you transplanted the comment and `:(` along with the fix 😆 We'll have to make a note to tackle this one as we start in on the responsive refactoring 😄

2019-03-07 02:20 UTC, SKuipers commented on IB Diploma/cas_student_myCommitments_delete.php
> +<!--
Looks like some dead code from the old form, now that you're done the refactor it's a great time to kill it 😃

2019-03-07 02:20 UTC, SKuipers commented on IB Diploma/cas_supervisor_invite.php
> +<!--
Some more dead code :)

2019-03-07 02:20 UTC, SKuipers commented on IB Diploma/staff_manage_addProcess.php
> +        var_dump ($gibbonPersonID);
👀  Debug output?

2019-03-07 02:20 UTC, SKuipers commented on IB Diploma/student_manage_add.php
> +		$row->addSelect('gibbonSchoolYearIDStart')->fromQuery($pdo, $sql)->placeholder(__('Please select...'))->isRequired();
Luckily the Select class will auto-add the `__('Please select...')` placeholders if the field is required. Helps cut down on a bit of code, and also helps if the text ever changes in the future.

2019-03-07 03:20 UTC, powertashton commented on IB Diploma/staff_manage_addProcess.php
> +        var_dump ($gibbonPersonID);
Yep, sorry.

2019-03-07 03:22 UTC, powertashton commented on IB Diploma/CHANGELOG.txt
> +v1.0.11
Done. Thank You 😄

2019-03-07 03:23 UTC, powertashton commented on IB Diploma/cas_adviseStudents_details.php
> +                                $valuesNum = 'even';
Yes please, that sounds interesting, can you send me the details?

2019-03-07 03:24 UTC, powertashton commented on IB Diploma/cas_adviseStudents_details.php
> +                                	echo "2_outcome".$i;
Was indeed a debug output, must've missed it when I was going through first time through, woops, sorry.

2019-03-07 03:26 UTC, powertashton commented on IB Diploma/cas_adviseStudents_details.php
> +							// HACK: Otherwise FastFinder width overrides this one :(
Yes, it had me stumped for a while, the `:(` did bring a smile to my face.

2019-03-07 03:35 UTC, powertashton commented
Yes I would be interested in taking the next steps for refactoring this module. Thanks

2019-03-12 04:27 UTC, SKuipers requested changes
Hi again! This is looking great, sorry for the wait (busy times at the moment!). I've installed it and tested it out, I think it's looking pretty close to merge-ready 👍  I noticed one small thing so-far, the `student_manage_edit.php` page is missing a `$form->loadAllValuesFrom($values);` at the bottom, to pre-fill the existing values. Aside from that, looks good, thanks!

2019-03-12 04:30 UTC, SKuipers commented
Oh, also be sure to catch the `$moduleVersion` in `version.php`. The version number tends to exist in four places: manifest.php, version.php, CHANGELOG.txt and CHANGEDB.php

2019-03-13 05:15 UTC, SKuipers approved these changes

2019-03-13 13:30 UTC, merged

2019-03-13 13:31 UTC, rossdotparker commented
Ash, it's amazing to see how much progress you've made on this. I've merged it, and now going to do some testing before releasing it on the website. Thanks : )

2019-03-13 13:39 UTC, rossdotparker commented
It's looking good. The only issue I can see so far is that adding a commitment with the following inputs (and any other inputs as far as I can see) returns a database error:

<img width="772" alt="Screenshot 2019-03-13 at 9 37 17 PM" src="https://user-images.githubusercontent.com/5436438/54283162-6918db80-45d8-11e9-93ac-6c8dde671278.png">

Do you want to look for and PR a fix for this, and then I can do some further testing. Thanks : )

2019-03-14 00:31 UTC, powertashton commented
Hi, @rossdotparker sorry I can't reproduce that error, on version 17 or 18. Is there something different on your system? Could you send me more debug information so I can double check what's going on?
![image](https://user-images.githubusercontent.com/48048360/54323242-55e72980-4633-11e9-9bb3-df4b8eba28ef.png)
![image](https://user-images.githubusercontent.com/48048360/54323247-5f709180-4633-11e9-9d25-50e078351b12.png)

2019-03-18 05:46 UTC, SKuipers commented
Hi Ashton,

I did a quick test on my system, looks like the error might be [SQL mode related](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html). Here is the error message: `General error: 1364 Field 'goals' doesn't have a default value` which results in an `error2` return value from line 101 of `cas_student_myCommitments_addProcess.php`. Looks like goals is defined as a `NOT NULL` field, so it needs a value passed in, even if that value is an empty string.

Lots of development installs like MAMP will not have the strict setting on, so the error often only turns up in production or on other people's systems 😅

2019-03-18 06:06 UTC, SKuipers commented
Here's some ideas for the next steps in refactoring:

- **Breadcrumbs**: check out the [PR here](https://github.com/GibbonEdu/core/issues/696) which has some instructions. We can add the IB module to the list 😃 

- **Code Cleanup**: The `@session_start();` & duplicate DB connections can be deleted, these are now handled by the core. Anytime you see the following at the top of a file it can safely be removed (& PRd)

```
//New PDO DB connection
try {
    $connection2 = new PDO("mysql:host=$databaseServer;dbname=$databaseName", $databaseUsername, $databasePassword);
    $connection2->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $connection2->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
} catch (PDOException $e) {
    echo $e->getMessage();
}

@session_start();
```

Also these timezone functions can be removed:
```
//Set timezone from session variable
date_default_timezone_set($_SESSION[$guid]['timezone']);
```

- **Refactoring Tables**: Much like the `Form` class, there's a set of `DataTable` classes for handling table data & lists of records. There's [an ooification guide here](https://gist.github.com/SKuipers/e176454a2feb555126c2147865bd0626). These can certainly get trickier than forms, feel free to give a shout on slack with any questions.

2019-03-19 13:56 UTC, rossdotparker commented
Hi @powertashton sorry for the delay in replying, but it looks like @SKuipers bailed me out. Let us know how you get on with this : )