Refactored staff_manage.php and student_manage.php tables
GibbonEdu/module-IBDiploma pull request #4
Opened 2020-04-14 11:21 UTC by powertashton

2020-04-21 01:23 UTC, SKuipers requested changes
This is looking great! As a note, the try/catch blocks are no longer necessary in queries that use the $pdo or gateway classes, the error handling is built-in. I've highlighted a couple here so that you can automatically remove them through the GitHub UI. Thanks!

2020-04-21 01:23 UTC, SKuipers commented on IB Diploma/staff_manage.php
>      try {
```suggestion

```

2020-04-21 01:23 UTC, SKuipers commented on IB Diploma/staff_manage.php
> +    } catch (PDOException $e) { $page->addError($e->getMessage());}
```suggestion

```

2020-04-21 01:23 UTC, SKuipers commented on IB Diploma/student_manage.php
>      try {
```suggestion

```

2020-04-21 01:23 UTC, SKuipers commented on IB Diploma/student_manage.php
> +    } catch (PDOException $e) { $page->addError(__('Students cannot be displayed.')); }
```suggestion
```

2020-06-17 08:11 UTC, powertashton commented
> This is looking great! As a note, the try/catch blocks are no longer necessary in queries that use the $pdo or gateway classes, the error handling is built-in. I've highlighted a couple here so that you can automatically remove them through the GitHub UI. Thanks!

Have noted this down for future reference and made the changes for this pull request... I totally didn't completely forget this pull request existed for two months

2020-10-13 04:55 UTC, SKuipers approved these changes
Wow, somehow this PR dropped off my radar too 😅 Going to merge and test it out now. Thanks!

2020-10-13 04:56 UTC, merged